spring.application.name=EVSeer
spring.config.import=env.properties

# Solar Power System
solarpower.provider.host=https://www.foxesscloud.com
solarpower.provider.path=/op/v0/device/real/query
solarpower.provider.token=${FOX_ESS_TOKEN}
solarpower.provider.sn=${DEVICE_SERIAL_NUMBER}

# Car charger / App
car.charger.app.url=https://openapi.tuyaeu.com
car.charger.app.auth.path=/v1.0/token?grant_type=1
car.charger.app.status.path=/v1.0/devices/status
car.charger.app.command.path=/v1.0/devices/{}/commands
car.charger.app.client.id=${CHARGER_CLIENT_ID}
car.charger.app.secret=${CHARGER_SECRET}
car.charger.device.id=${CHARGER_DEVICE_ID}

# Voltage of socket where charger is connected
charging.electrical.outlet.voltage=220